# Generated by Django 3.0.5 on 2020-04-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=12)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NumberFactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentNo', models.IntegerField()),
                ('lastDate', models.DateField()),
                ('prefix', models.CharField(max_length=20)),
                ('suffixSize', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=12)),
                ('accountBalance', models.FloatField()),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('registryDate', models.DateTimeField()),
                ('cancelDate', models.DateTimeField()),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'unique_together': {('name', 'status')},
            },
        ),
    ]
