# Generated by Django 3.0.5 on 2020-04-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=12)),
                ('accountBalance', models.FloatField()),
                ('sex', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
